set $mode_screenshot "s  | f  | e  | o  | u  | r  | a  "

mode $mode_screenshot {
    $bindsym s mode "default", exec $screenshot_copy_area
    $bindsym f mode "default", exec $screenshot_copy_save_area
    $bindsym e mode "default", exec $screenshot_edit_area
    $bindsym o mode "default", exec $screenshot_save_screen
    $bindsym u mode "default", exec $screenshot_upload_area

    $bindsym r exec $recorder, mode "default"
    $bindsym a exec $recorder -a, mode "default"

    $bindsym Escape mode "default"
}

## Launch // Screenshot Mode ##
$bindsym Print mode $mode_screenshot
$bindsym $mod+Shift+s mode $mode_screenshot
$bindsym $mod+Escape exec killall -s SIGINT wf-recorder
